FROM nginx

RUN apt-get update
RUN apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash

RUN apt-get install -y nodejs

COPY package.json /app/
COPY package-lock.json /app/

WORKDIR /app/

RUN npm install

COPY . /app/

RUN npm run -- bundle

RUN cp -r website/* /usr/share/nginx/html/

RUN mkdir /usr/share/nginx/html/lib
RUN cp dist/covid19/bundle-es2015.js /usr/share/nginx/html/lib/
RUN cp dist/covid19/bundle-es5.js /usr/share/nginx/html/lib/

COPY nginx/default.conf /etc/nginx/conf.d/
COPY nginx/htpasswd /etc/nginx/htpasswd

EXPOSE 80
